: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX ICa_LVA
    USEION ca WRITE ica
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = 0.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ica (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ica = g * ( var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = 1.0/(exp(-0.16666666666666666*v - 6.6666666666666661) + 1.0)
    tau0 = 5.0 + 6.7796610169491522/(exp(0.20000000000000001*v + 7.0) + 1.0)
    var1inf = 1.0/(exp(0.15625*v + 14.0625) + 1.0)
    tau1 = 20.0 + 16.949152542372879/(exp(0.14285714285714285*v + 7.1428571428571423) + 1.0)
}

