: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX ICa_HVA
    USEION ca WRITE ica
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = 0.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ica (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ica = g * ( var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = (-0.055*v - 1.4850000000000001)/(((-0.055*v - 1.4850000000000001)/(exp(-0.26315789473684209*v - 7.1052631578947363) - 1.0) + 0.012133746930834877*0.93999999999999995*exp(-0.058823529411764705*v))*(exp(-0.26315789473684209*v - 7.1052631578947363) - 1.0))
    tau0 = 1.0/((-0.055*v - 1.4850000000000001)/(exp(-0.26315789473684209*v - 7.1052631578947363) - 1.0) + 0.012133746930834877*0.93999999999999995*exp(-0.058823529411764705*v))
    var1inf = 0.00035237057471222975*exp(-0.02*v)/(0.000457*0.77105158580356625*exp(-0.02*v) + 0.0064999999999999997/(exp(-0.035714285714285712*v - 0.5357142857142857) + 1.0))
    tau1 = 1.0/(0.000457*0.77105158580356625*exp(-0.02*v) + 0.0064999999999999997/(exp(-0.035714285714285712*v - 0.5357142857142857) + 1.0))
}

