: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX Ih_HAY
    NONSPECIFIC_CURRENT i
    RANGE  g, e
    GLOBAL var0inf, tau0
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = 0.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    i (mA/cm2)
    var0inf
    tau0 (ms)
    v (mV)
}

STATE {
    var0
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    i = g * ( var0 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
}

PROCEDURE rates(v) {
    var0inf = (0.00643*v + 0.99600699999999998)/(((0.00643*v + 0.99600699999999998)/(exp(0.084033613445378144*v + 13.016806722689076) - 1.0) + 0.193*exp(0.030211480362537763*v))*(exp(0.084033613445378144*v + 13.016806722689076) - 1.0))
    tau0 = 1.0/((0.00643*v + 0.99600699999999998)/(exp(0.084033613445378144*v + 13.016806722689076) - 1.0) + 0.193*exp(0.030211480362537763*v))
}

