: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX IKpst
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = 0.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * ( var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = 1.0/(exp(-0.083333333333333329*v - 0.91666666666666663) + 1.0)
    tau0 = 1.0305084745762711 + 5.8644067796610173*exp(-pow(0.062893081761006289*v + 3.7735849056603774, 2)) + 8.5423728813559308*exp(-pow(0.017421602787456445*v + 1.0452961672473866, 2))
    var1inf = 1.0/(exp(0.090909090909090912*v + 5.8181818181818183) + 1.0)
    tau1 = 0.33898305084745761*(24.0*v + 2570.0)*exp(-pow(0.020833333333333332*v + 1.7708333333333333, 2)) + 122.03389830508473
}

