: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX IKtst
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = 0.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * ( var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = 1.0/(exp(-0.052631578947368418*v - 0.52631578947368418) + 1.0)
    tau0 = 0.11525423728813559 + 0.31186440677966104*exp(-pow(0.016949152542372881*v + 1.3728813559322033, 2))
    var1inf = 1.0/(exp(0.10000000000000001*v + 7.6000000000000005) + 1.0)
    tau1 = 2.7118644067796609 + 16.610169491525422*exp(-pow(0.043478260869565216*v + 3.6086956521739131, 2))
}

