: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX INa_Ta
    USEION na WRITE ina
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = 0.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ina (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ina = g * ( var0 * var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = (0.182*v + 6.9159999999999995)/((1.0 - 0.0017761035457343791*exp(-0.16666666666666666*v))*((-0.124*v - 4.7119999999999997)/(-563.03023683595109*exp(0.16666666666666666*v) + 1.0) + (0.182*v + 6.9159999999999995)/(1.0 - 0.0017761035457343791*exp(-0.16666666666666666*v))))
    tau0 = 0.33898305084745761/((-0.124*v - 4.7119999999999997)/(-563.03023683595109*exp(0.16666666666666666*v) + 1.0) + (0.182*v + 6.9159999999999995)/(1.0 - 0.0017761035457343791*exp(-0.16666666666666666*v)))
    var1inf = (-0.014999999999999999*v - 0.98999999999999999)/((-59874.141715197817*exp(0.16666666666666666*v) + 1.0)*((-0.014999999999999999*v - 0.98999999999999999)/(-59874.141715197817*exp(0.16666666666666666*v) + 1.0) + (0.014999999999999999*v + 0.98999999999999999)/(1.0 - 1.6701700790245659e-5*exp(-0.16666666666666666*v))))
    tau1 = 0.33898305084745761/((-0.014999999999999999*v - 0.98999999999999999)/(-59874.141715197817*exp(0.16666666666666666*v) + 1.0) + (0.014999999999999999*v + 0.98999999999999999)/(1.0 - 1.6701700790245659e-5*exp(-0.16666666666666666*v)))
}

