: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX ITestChannel
    NONSPECIFIC_CURRENT i
    RANGE  g, e
    GLOBAL var0inf, var1inf, var2inf, var3inf, var4inf, var5inf, tau0, tau1, tau2, tau3, tau4, tau5
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = 0.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    i (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    var2inf
    tau2 (ms)
    var3inf
    tau3 (ms)
    var4inf
    tau4 (ms)
    var5inf
    tau5 (ms)
    v (mV)
}

STATE {
    var0
    var1
    var2
    var3
    var4
    var5
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    i = g * ( var0 * var0 * var0 * var1 * var1 * var1 * var2 *5.0 +  var3 * var3 * var4 * var4 * var5 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
    var2 = var2inf
    var3 = var3inf
    var4 = var4inf
    var5 = var5inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
    var2' = (var2inf - var2) / tau2
    var3' = (var3inf - var3) / tau3
    var4' = (var4inf - var4) / tau4
    var5' = (var5inf - var5) / tau5
}

PROCEDURE rates(v) {
    var0inf = 1.0/(exp(0.01*v - 0.29999999999999999) + 1.0)
    tau0 = 1.0
    var1inf = 1.0/(exp(-0.01*v + 0.29999999999999999) + 1.0)
    tau1 = 2.0
    var2inf = -10.0
    tau2 = 1.0
    var3inf = 2.0/(exp(0.01*v - 0.29999999999999999) + 1.0)
    tau3 = 2.0
    var4inf = 2.0/(exp(-0.01*v + 0.29999999999999999) + 1.0)
    tau4 = 2.0
    var5inf = -30.0
    tau5 = 3.0
}

